apiVersion: apps/v1
kind: Deployment
metadata:
  name: web_scraping_deployment
spec:
  selector:
    matchLabels:
      app: web_scraping_pod
  template:
    metadata:
      labels:
        app: web_scraping_pod
    spec:
      containers:
      - name: web_scraping_container
        image: web_scraping:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
