apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-scraping-deployment
spec:
  selector:
    matchLabels:
      app: web-scraping-pod
  template:
    metadata:
      labels:
        app: web-scraping-pod
    spec:
      containers:
      - name: web-scraping-container
        image: web-scraping:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
